import { StudentProfile } from "@/lib/types";

export const MOCK_STUDENTS: StudentProfile[] = [
  {
    id: "student-01",
    name: "학생01",
    department: "컴퓨터공학과",
    year: 3,
    bio: "웹 서비스 구조를 설계하고 빠르게 프로토타입을 만드는 데 관심이 많습니다.",
    role: "개발자",
    collaborationStyle: "협력형",
    interests: ["웹개발", "오픈소스", "보드게임", "독서"],
    skills: ["React", "TypeScript", "Node.js"],
    lookingFor: ["디자이너", "PM"],
    avatarInitial: "01",
  },
  {
    id: "student-02",
    name: "학생02",
    department: "시각디자인학과",
    year: 2,
    bio: "브랜딩과 UI 디자인을 좋아하고, 사용자가 바로 이해하는 화면을 만들고 싶습니다.",
    role: "디자이너",
    collaborationStyle: "서포터형",
    interests: ["브랜딩", "전시회", "사진", "카페투어"],
    skills: ["Figma", "Illustrator", "Photoshop"],
    lookingFor: ["개발자", "마케터"],
    avatarInitial: "02",
  },
  {
    id: "student-03",
    name: "학생03",
    department: "경영학과",
    year: 4,
    bio: "문제 정의와 일정 조율을 맡는 것을 좋아하며, 팀이 같은 방향을 보도록 돕습니다.",
    role: "PM",
    collaborationStyle: "리더형",
    interests: ["스타트업", "기획", "운동", "독서"],
    skills: ["서비스기획", "Notion", "PPT"],
    lookingFor: ["개발자", "디자이너"],
    avatarInitial: "03",
  },
  {
    id: "student-04",
    name: "학생04",
    department: "데이터사이언스학과",
    year: 3,
    bio: "데이터로 사용자의 행동을 해석하고, 숫자로 가설을 검증하는 작업을 좋아합니다.",
    role: "데이터분석가",
    collaborationStyle: "독립형",
    interests: ["데이터", "AI", "체스", "러닝"],
    skills: ["Python", "SQL", "Tableau"],
    lookingFor: ["PM", "마케터"],
    avatarInitial: "04",
  },
  {
    id: "student-05",
    name: "학생05",
    department: "미디어커뮤니케이션학과",
    year: 2,
    bio: "콘텐츠 기획과 SNS 운영에 관심이 많고, 사람들의 반응을 분석하는 것을 좋아합니다.",
    role: "마케터",
    collaborationStyle: "협력형",
    interests: ["콘텐츠", "SNS", "영화", "트렌드"],
    skills: ["콘텐츠기획", "카피라이팅", "Instagram"],
    lookingFor: ["디자이너", "데이터분석가"],
    avatarInitial: "05",
  },
  {
    id: "student-06",
    name: "학생06",
    department: "소프트웨어학과",
    year: 1,
    bio: "모바일 앱 개발을 배우는 중이며, 작은 기능도 끝까지 완성하는 편입니다.",
    role: "개발자",
    collaborationStyle: "독립형",
    interests: ["모바일", "게임개발", "음악", "산책"],
    skills: ["Flutter", "Kotlin", "Firebase"],
    lookingFor: ["디자이너", "PM"],
    avatarInitial: "06",
  },
  {
    id: "student-07",
    name: "학생07",
    department: "산업디자인학과",
    year: 4,
    bio: "사용자 리서치와 제품 콘셉트 정리에 강점이 있고, 피드백을 꼼꼼히 반영합니다.",
    role: "디자이너",
    collaborationStyle: "협력형",
    interests: ["UX리서치", "제품디자인", "여행", "드로잉"],
    skills: ["Figma", "User Research", "Prototyping"],
    lookingFor: ["개발자", "PM"],
    avatarInitial: "07",
  },
  {
    id: "student-08",
    name: "학생08",
    department: "산업공학과",
    year: 3,
    bio: "복잡한 요구사항을 정리하고 우선순위를 세우는 일을 좋아합니다.",
    role: "PM",
    collaborationStyle: "서포터형",
    interests: ["생산성", "프로젝트관리", "퍼즐", "야구"],
    skills: ["Jira", "일정관리", "요구사항정리"],
    lookingFor: ["개발자", "데이터분석가"],
    avatarInitial: "08",
  },
  {
    id: "student-09",
    name: "학생09",
    department: "통계학과",
    year: 2,
    bio: "설문과 실험 데이터를 분석해 의미 있는 인사이트를 찾는 데 흥미가 있습니다.",
    role: "데이터분석가",
    collaborationStyle: "협력형",
    interests: ["통계", "설문분석", "축구", "요리"],
    skills: ["R", "Python", "Excel"],
    lookingFor: ["마케터", "PM"],
    avatarInitial: "09",
  },
  {
    id: "student-10",
    name: "학생10",
    department: "광고홍보학과",
    year: 3,
    bio: "캠페인 메시지와 타깃 전략을 고민하는 것을 좋아하고 발표에 자신 있습니다.",
    role: "마케터",
    collaborationStyle: "리더형",
    interests: ["광고", "브랜드", "공연", "글쓰기"],
    skills: ["브랜드전략", "SNS운영", "발표"],
    lookingFor: ["디자이너", "개발자"],
    avatarInitial: "10",
  },
  {
    id: "student-11",
    name: "학생11",
    department: "정보보호학과",
    year: 4,
    bio: "백엔드와 보안에 관심이 많고, 안정적인 시스템을 만드는 일을 선호합니다.",
    role: "개발자",
    collaborationStyle: "서포터형",
    interests: ["보안", "백엔드", "클라이밍", "독서"],
    skills: ["Java", "Spring", "Docker"],
    lookingFor: ["PM", "데이터분석가"],
    avatarInitial: "11",
  },
  {
    id: "student-12",
    name: "학생12",
    department: "디지털콘텐츠학과",
    year: 1,
    bio: "모션 그래픽과 인터랙션 디자인을 배우고 있으며 시각적인 완성도를 중시합니다.",
    role: "디자이너",
    collaborationStyle: "독립형",
    interests: ["모션그래픽", "3D", "애니메이션", "음악"],
    skills: ["After Effects", "Blender", "Figma"],
    lookingFor: ["개발자", "마케터"],
    avatarInitial: "12",
  },
  {
    id: "student-13",
    name: "학생13",
    department: "창업학과",
    year: 2,
    bio: "아이디어를 빠르게 검증하고 사용자 반응을 보며 방향을 바꾸는 방식을 좋아합니다.",
    role: "PM",
    collaborationStyle: "리더형",
    interests: ["창업", "MVP", "네트워킹", "독서"],
    skills: ["린캔버스", "인터뷰", "피칭"],
    lookingFor: ["개발자", "디자이너", "마케터"],
    avatarInitial: "13",
  },
  {
    id: "student-14",
    name: "학생14",
    department: "빅데이터학과",
    year: 4,
    bio: "추천 시스템과 로그 분석에 관심이 있고, 모델 성능 개선을 차분히 파고듭니다.",
    role: "데이터분석가",
    collaborationStyle: "독립형",
    interests: ["추천시스템", "머신러닝", "농구", "사진"],
    skills: ["Python", "PyTorch", "BigQuery"],
    lookingFor: ["개발자", "PM"],
    avatarInitial: "14",
  },
  {
    id: "student-15",
    name: "학생15",
    department: "국제통상학과",
    year: 3,
    bio: "시장 조사와 경쟁사 분석을 좋아하며, 자료를 설득력 있게 정리하는 데 강점이 있습니다.",
    role: "마케터",
    collaborationStyle: "서포터형",
    interests: ["시장조사", "해외브랜드", "여행", "뉴스"],
    skills: ["시장분석", "리서치", "Excel"],
    lookingFor: ["PM", "데이터분석가"],
    avatarInitial: "15",
  },
  {
    id: "student-16",
    name: "학생16",
    department: "컴퓨터공학과",
    year: 2,
    bio: "프론트엔드 인터랙션 구현을 좋아하고, 디자이너와 화면을 맞춰가는 과정이 즐겁습니다.",
    role: "개발자",
    collaborationStyle: "협력형",
    interests: ["프론트엔드", "UI", "게임", "자전거"],
    skills: ["React", "CSS", "Next.js"],
    lookingFor: ["디자이너", "마케터"],
    avatarInitial: "16",
  },
  {
    id: "student-17",
    name: "학생17",
    department: "커뮤니케이션디자인학과",
    year: 3,
    bio: "정보 구조와 화면 흐름을 정리하는 데 관심이 많고, 사용성 테스트를 좋아합니다.",
    role: "디자이너",
    collaborationStyle: "리더형",
    interests: ["UX", "서비스디자인", "전시", "필름카메라"],
    skills: ["Wireframe", "Figma", "Usability Test"],
    lookingFor: ["개발자", "데이터분석가"],
    avatarInitial: "17",
  },
  {
    id: "student-18",
    name: "학생18",
    department: "문헌정보학과",
    year: 4,
    bio: "사용자 요구를 정리하고 정보 탐색 과정을 개선하는 프로젝트에 관심이 있습니다.",
    role: "PM",
    collaborationStyle: "협력형",
    interests: ["정보검색", "서비스기획", "독서", "기록"],
    skills: ["문서화", "사용자조사", "Notion"],
    lookingFor: ["개발자", "디자이너"],
    avatarInitial: "18",
  },
  {
    id: "student-19",
    name: "학생19",
    department: "응용통계학과",
    year: 1,
    bio: "데이터 시각화를 통해 복잡한 내용을 쉽게 설명하는 작업을 해보고 싶습니다.",
    role: "데이터분석가",
    collaborationStyle: "서포터형",
    interests: ["시각화", "통계", "러닝", "영화"],
    skills: ["Python", "Tableau", "Google Sheets"],
    lookingFor: ["마케터", "디자이너"],
    avatarInitial: "19",
  },
  {
    id: "student-20",
    name: "학생20",
    department: "문화콘텐츠학과",
    year: 2,
    bio: "브랜드 스토리와 커뮤니티 운영에 관심이 많고, 사람들의 참여를 끌어내고 싶습니다.",
    role: "마케터",
    collaborationStyle: "협력형",
    interests: ["커뮤니티", "콘텐츠", "공연", "글쓰기"],
    skills: ["커뮤니티운영", "카피라이팅", "콘텐츠캘린더"],
    lookingFor: ["디자이너", "PM"],
    avatarInitial: "20",
  },
  {
    id: "student-21",
    name: "학생21",
    department: "인공지능학과",
    year: 3,
    bio: "AI 기능을 서비스에 붙이는 작업에 관심이 있고, 실험적인 구현을 즐깁니다.",
    role: "개발자",
    collaborationStyle: "독립형",
    interests: ["AI", "챗봇", "음악", "게임"],
    skills: ["Python", "FastAPI", "OpenAI API"],
    lookingFor: ["PM", "데이터분석가"],
    avatarInitial: "21",
  },
  {
    id: "student-22",
    name: "학생22",
    department: "패션디자인학과",
    year: 4,
    bio: "트렌드와 비주얼 콘셉트를 빠르게 잡는 편이고, 감각적인 결과물을 만들고 싶습니다.",
    role: "디자이너",
    collaborationStyle: "서포터형",
    interests: ["패션", "트렌드", "사진", "전시"],
    skills: ["Moodboard", "Photoshop", "Illustrator"],
    lookingFor: ["마케터", "개발자"],
    avatarInitial: "22",
  },
  {
    id: "student-23",
    name: "학생23",
    department: "행정학과",
    year: 3,
    bio: "정책과 공공서비스 문제를 사용자 관점에서 풀어보는 프로젝트에 관심이 있습니다.",
    role: "PM",
    collaborationStyle: "독립형",
    interests: ["공공서비스", "정책", "토론", "등산"],
    skills: ["문제정의", "리서치", "보고서작성"],
    lookingFor: ["데이터분석가", "개발자"],
    avatarInitial: "23",
  },
  {
    id: "student-24",
    name: "학생24",
    department: "경제학과",
    year: 2,
    bio: "사용자 지표와 시장 데이터를 연결해 성장 전략을 세우는 일을 해보고 싶습니다.",
    role: "데이터분석가",
    collaborationStyle: "리더형",
    interests: ["그로스", "경제", "야구", "뉴스레터"],
    skills: ["SQL", "Excel", "GA4"],
    lookingFor: ["마케터", "PM"],
    avatarInitial: "24",
  },
  {
    id: "student-25",
    name: "학생25",
    department: "광고홍보학과",
    year: 1,
    bio: "짧고 강한 메시지를 만드는 것을 좋아하고, 실험적인 홍보 아이디어를 자주 냅니다.",
    role: "마케터",
    collaborationStyle: "독립형",
    interests: ["숏폼", "광고", "밈", "음악"],
    skills: ["숏폼기획", "카피라이팅", "영상편집"],
    lookingFor: ["디자이너", "개발자"],
    avatarInitial: "25",
  },
];

export async function fetchStudents(): Promise<StudentProfile[]> {
  await new Promise((resolve) => setTimeout(resolve, 500));

  return MOCK_STUDENTS;
}
